apiVersion: skaffold/v4beta10
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*.yaml
build:
  artifacts:
    - image: doyakonnga/auth
      context: ./auth
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: doyakonnga/cost
      context: ./cost
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: doyakonnga/photo
      context: ./photo
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: doyakonnga/client
      context: ./client
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
  