FROM node:alpine

WORKDIR /app
COPY package.json .
RUN npm i
COPY . .
# RUN npx prisma migrate dev

# CMD ["npm", "run", "test-in-docker-compose"]
CMD npx prisma migrate dev && npx jest --watchAll --no-cache --runInBand