# version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres_auth
    environment:
      POSTGRES_USER: test
      POSTGRES_DB: auth
      POSTGRES_HOST_AUTH_METHOD: trust
  app:
    build: 
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    ports: 
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://test:test@postgres:5432/auth
    depends_on:
      - postgres
