
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cookies } from 'next/headers'
import axios from 'axios'
import Header from '@/components/header'


const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'TravelNote',
  description: 'Generated by create next app',
}

declare global {
  interface CurrentUser {
    id: string
    email: string
    name: string
    avatar: string
    journeyIds: string[]
  }

  interface Member {
    id: string
    name: string
    avatar: string
  }

  interface Journey {
    id: string
    name: string
    subtitle: string | null
    picture: string | null
    members: Member[]
  }

  type Expense = {
    id: string
    userId: string
    amount: number
    isPaid: boolean
  }

  type Consumption = {
    id: string
    name: string
    isForeign: boolean
    rate: number
    payingUserId: string
    journeyId: string
    createdAt: string
    expenses: Expense[]
  }
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const Cookie = cookies().getAll().map((c) => {
    return `${c.name}=${c.value};`
  }).join(' ')
  let currentUser: CurrentUser | null = null
  try {
    currentUser = (await axios.get('http://ingress-nginx-controller.ingress-nginx.svc.cluster.local/api/v1/user/currentuser', {
      headers: {
        Host: "travelnote.com",
        Cookie
      }
    }
    )).data.user
  } catch (e) {
    console.log(e)
  }


  return (
    <html lang="en">
      <body className="h-dvh bg-neutral-300">
        <Header currentUser={currentUser} />
        {children}
      </body>
    </html>
  )
}
